name: Update Gruntwork Pipelines PR Status
description: "Update Gruntwork Pipelines PR Status"

runs:
  using: composite
  steps:
    - name: Calculate Table
      shell: bash
      run: |
        echo "Preflight checks result: ${{ jobs.preflight_checks.result }}"
        echo "detect_changes result: ${{ jobs.detect_changes.result }}"
        echo "pipelines_determine result: ${{ jobs.pipelines_determine.result }}"
    - name: Create comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          Gruntwork Pipelines started...
          [${{ jobs.preflight_checks.result }}] Preflight Checks
          [${{ jobs.detect_changes.result }}] Detect Changes
          [${{ jobs.pipelines_determine.result }}] Pipelines Determine
