name: Update Gruntwork Pipelines PR Status
description: "Update Gruntwork Pipelines PR Status"

runs:
  using: composite
  steps:
    - name: Calculate Table
      shell: bash
      run: |
        echo "Preflight checks outcome: ${{ steps.preflight_checks.outcome }}"
        echo "detect_changes outcome: ${{ steps.detect_changes.outcome }}"
        echo "pipelines_determine: ${{ steps.pipelines_determine.outcomes }}"
    - name: Create comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          Gruntwork Pipelines started...
          [ ] Preflight Checks
