name: Update Gruntwork Pipelines PR Status
description: "Update Gruntwork Pipelines PR Status"
inputs:
  preflight_checks:
    description: "Status of preflight checks step"
    default: 'not_started'
  detect_changes:
    description: "Status of preflight checks step"
    default: 'not_started'
  pipelines_determine:
    description: "Status of preflight checks step"
    default: 'not_started'

runs:
  using: composite
  steps:
    - name: Calculate Table
      shell: bash
      run: |
        echo "Preflight checks result: ${{ inputs.preflight_checks }}"
        echo "detect_changes result: ${{ inputs.detect_changes }}"
        echo "pipelines_determine result: ${{ inputs.pipelines_determine }}"
    - name: Create comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          Gruntwork Pipelines started...
          [${{ inputs.preflight_checks }}] Preflight Checks
          [${{ inputs.detect_changes }}] Detect Changes
          [${{ inputs.pipelines_determine }}] Pipelines Determine
